# Generated by Django 5.2.7 on 2025-10-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person contacting us', max_length=200)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20)),
                ('subject', models.CharField(help_text='Subject of the inquiry', max_length=300)),
                ('message', models.TextField(help_text='Detailed message')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when message was received')),
                ('read', models.BooleanField(default=False, help_text='Mark as read/unread')),
                ('notes', models.TextField(blank=True, help_text='Internal notes (visible only to admin)')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
